### ISSUE TITLE
assign $new function to all scopes and not only isolated

### ISSUE THREAD

**Issue by edenpessach** [js-black-belt/angular-ticker#18]
Current:
   if (isolate) {
-                    newScope.unregisterTickerTask = $rootScope.unregisterTickerTask;
-                    newScope.registerTickerTask = $rootScope.registerTickerTask;
-                    newScope.$new = newNew(newScope); 
-                }

Should be:
   if (isolate) {
-                    newScope.unregisterTickerTask = $rootScope.unregisterTickerTask;
-                    newScope.registerTickerTask = $rootScope.registerTickerTask;
-                }
-                    newScope.$new = newNew(newScope);  //// It should be outside of the if statement

**Comment by sefininio** [comment]
I disagree.
Could you explain why?

My tests expect both isolated and non-isolated child scopes of both isolates and non-isolated scopes to have the scope API. The tests pass.

Logically, I only want to override the $new function for isolated scopes. 
Could you provide a scenario that demonstrates a scope that does not have the scope API with the current implementation?
Also, please make sure you are using the latest version, it doesn't seem that way.

**Comment by edenpessach** [comment]
http://plnkr.co/edit/I7mZQtU3iR2LqDT6XtHe?p=preview

**Comment by sefininio** [comment]
I recommend reading this:
http://angular-tips.com/blog/2014/03/transclusion-and-scopes/

The way you implement ngTransclude is in your hands. The tickerSrv responsibility is to make sure that isolated scopes get the scope API, and they do (see the tests).

**Comment by sefininio** [comment]
The tests I run (which all pass) test multiple inheritance options of multiple degrees:
            expect(scope.$new).toBeDefined();
            expect(scope.registerTickerTask).toBeDefined();
            expect(isolatedScope.$new).toBeDefined();
            expect(isolatedScope.registerTickerTask).toBeDefined();

```
        // new scope from scope
        expect(scope.$new().registerTickerTask).toBeDefined();

        // new isolated scope from scope
        expect(scope.$new(true).registerTickerTask).toBeDefined();

        // new scope from isolated scope
        expect(isolatedScope.$new().registerTickerTask).toBeDefined();

        // new isolated scope from isolated scope
        expect(isolatedScope.$new(true).registerTickerTask).toBeDefined();

        expect(scope.$new(true).$new().registerTickerTask).toBeDefined();
        expect(scope.$new(true).$new(true).registerTickerTask).toBeDefined();
        expect(isolatedScope.$new(true).$new().registerTickerTask).toBeDefined();
        expect(isolatedScope.$new(true).$new(true).registerTickerTask).toBeDefined();
```

**Comment by sefininio** [comment]
A _working_ plunk based on yours:
http://plnkr.co/edit/QFq5fbqJ7IKcicnjbSvQ?p=preview

**Comment by sefininio** [comment]
Even your original plunk shows that the transcluded scope includes the scope API (examine the console):
http://plnkr.co/edit/wItSvOklB4zza7Ig4m11?p=preview
